export const SAVE_GOOGLE = 'SAVE_GOOGLE';
export const SAVE_MAP = 'SAVE_MAP';
export const SAVE_PLACES_SERVICE = 'SAVE_PLACES_SERVICE';

export const TOGGLE_MAP_LOADING = 'TOGGLE_MAP_LOADING';
export const SELECT_MARKER = 'SELECT_MARKER';
export const DESELECT_MARKER = 'DESELECT_MARKER';
export const HOVER_MARKER = 'HOVER_MARKER';
export const UNHOVER_MARKER = 'UNHOVER_MARKER';
export const REPLACE_MARKERS_WITH_NEW = 'REPLACE_MARKERS_WITH_NEW';
export const SAVE_MAP_CONFIG = 'SAVE_MAP_CONFIG';

export const SAVE_GEOLOCATION = 'SAVE_GEOLOCATION';
